language: node_js
node_js:
  - node
git:
  depth: 2
  quiet: true
install:
  - npm set audit false
  - npm i
script:
  - node ./index.js
cache:
  directories:
    - "node_modules"
branches:
  - master
